"""add assettype column to InvestmentInformation

Revision ID: 26d84c38cb51
Revises: 8416a861517d
Create Date: 2025-04-24 09:38:48.466175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d84c38cb51'
down_revision = '8416a861517d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_type', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('fk_investment_information_portfolio_id_portfolios', type_='foreignkey')
        batch_op.drop_column('portfolio_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portfolio_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_investment_information_portfolio_id_portfolios', 'portfolios', ['portfolio_id'], ['id'])
        batch_op.drop_column('asset_type')

    # ### end Alembic commands ###
