"""Add InvestmentInformation model

Revision ID: 8416a861517d
Revises: 7366c6b1b3cc
Create Date: 2025-04-23 23:14:12.129284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8416a861517d'
down_revision = '7366c6b1b3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_investment_information_portfolio_id_portfolios')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment_information')
    # ### end Alembic commands ###
